---
language: go

go:
  - 1.x

services:
  - docker

before_install:
  - sudo apt-get install qemu-utils
  - docker build . --tag machacekondra/fakeovirt
  - docker run -e NAMESPACE=cdi-test -d -p 127.0.0.1:12346:12346 machacekondra/fakeovirt
  - docker ps -a

script:
  - curl -k https://127.0.0.1:12345/images/cirros -o cirros.img
  - qemu-img check cirros.img
