---
language: go

go:
  - 1.x

services:
  - docker

before_install:
  - sudo apt-get install qemu-utils
  - docker build . --tag machacekondra/imageiotest
  - docker run -d -p 127.0.0.1:12345:12345 machacekondra/imageiotest
  - docker ps -a

script:
  - curl -k https://127.0.0.1:12345/images/cirros -o image.img
  - qemu-img info image.img
